#!/usr/bin/env bash

set -e

# Build each image
#
# Note that each image is built in a subdirectory to avoid breaking
# Docker's caching.
#
# Note too that all these commands except the final rvt command
# make snapshots of git repos.
# Images should be deleted and rebuilt to get any changes from the
# git repos.

(cd docker/base    && ../mkimage rvt_base       Dockerfile)
(cd docker/rustc   && ../mkimage rvt_rustc      Dockerfile)
(cd docker/minisat && ../mkimage rvt_minisat    Dockerfile)
(cd docker/stp     && ../mkimage rvt_stp        Dockerfile)
(cd docker/klee    && ../mkimage rvt_klee       Dockerfile)
(cd docker/z3      && ../mkimage rvt_z3         Dockerfile)
(cd docker/yices   && ../mkimage rvt_yices      Dockerfile)
(cd docker/seahorn && ../mkimage rvt_seahorn    Dockerfile)
(cd docker/rvt     && ../mkimage rvt            Dockerfile)
