#!/usr/bin/env bash

set -e

# Before building the docker image, we ensure that the
# rvt-patch-llvm source code will be available when building rvt
# by copying it into a subdirectory of docker/rvt.
# (Note that it is not sufficient to use a symlink - you actually
# have to make a copy. I hate Docker so much right now.)
(cd rvt-patch-llvm; cargo clean)
rm -rf docker/rvt/rvt-patch-llvm
cp -r `pwd`/rvt-patch-llvm docker/rvt/rvt-patch-llvm

# Copy cargo-verify over
cargo clean --manifest-path cargo-verify/Cargo.toml
rm -rf docker/rvt/cargo-verify
cp -a `pwd`/cargo-verify docker/rvt/cargo-verify

# Build each image
#
# Note that each image is built in a subdirectory to avoid breaking
# Docker's caching.
#
# Note too that all these commands except the final rvt command
# make snapshots of git repos.
# Images should be deleted and rebuilt to get any changes from the
# git repos.

(cd docker/base    && ../mkimage rvt_base       Dockerfile)
(cd docker/rustc   && ../mkimage rvt_rustc      Dockerfile)
(cd docker/minisat && ../mkimage rvt_minisat    Dockerfile)
(cd docker/stp     && ../mkimage rvt_stp        Dockerfile)
(cd docker/klee    && ../mkimage rvt_klee       Dockerfile)
(cd docker/z3      && ../mkimage rvt_z3         Dockerfile)
(cd docker/yices   && ../mkimage rvt_yices      Dockerfile)
(cd docker/seahorn && ../mkimage rvt_seahorn    Dockerfile)
(cd docker/rvt     && ../mkimage rvt            Dockerfile)
