#!/usr/bin/env bash

echo To build LLVM11 version, use 'env LLVM11=yes docker/build'

set -e

# Build each image
#
# Note that each image is built in a subdirectory to avoid breaking
# Docker's caching.
#
# Note too that all these commands except the final rvt command
# make snapshots of git repos.
# Images should be deleted and rebuilt to get any changes from the
# git repos.

(cd docker/base    && ../mkimage rvt_base       Dockerfile)
(cd docker/solvers && ../mkimage rvt_solvers    Dockerfile)
(cd docker/klee    && ../mkimage rvt_klee       Dockerfile)
(cd docker/rmc     && ../mkimage rvt_rmc        Dockerfile)
(cd docker/seahorn && ../mkimage rvt_seahorn    Dockerfile)

# This does not run in a subdirectory so it will copy everything over.
# This is really unfortunate but it allows us to run docker/init
# to prebuild all our scripts/libraries.
docker/mkimage rvt docker/rvt/Dockerfile

# Optional: verification profiling support
# Note that this creates a VERY LARGE image including X11, kcachegrind and lots more
# (cd docker/rust2calltree && ../mkimage rvt_r2ct Dockerfile)
