#!/usr/bin/env bash

readonly DOCKER_IMAGE_NAME="$1"
readonly DOCKER_FILE="$2"
readonly DOCKER_VERSION="latest"

echo Making docker image ${DOCKER_IMAGE_NAME}:${DOCKER_VERSION} using ${DOCKER_FILE}

# The default user for a Docker container has uid 0 (root). To avoid creating
# root-owned files in the build directory we tell Docker to use the current user
# ID, if known.
# See
# https://github.com/googleapis/google-cloud-cpp/blob/a186208b79d900b4ec71c6f9df3acf7638f01dc6/ci/kokoro/docker/build.sh#L147-L152
readonly DOCKER_UID="${UID:-0}"
readonly DOCKER_GID="$(id -g)"
readonly DOCKER_USER="${USER:-root}"

sudo docker build \
  --file=${DOCKER_FILE} \
  --cache-from="${DOCKER_IMAGE_NAME}:${DOCKER_VERSION}" \
  --tag="${DOCKER_IMAGE_NAME}:${DOCKER_VERSION}" \
  --build-arg=USERNAME="$DOCKER_USER" \
  --build-arg=USER_UID="$DOCKER_UID" \
  --build-arg=USER_GID="$DOCKER_GID" \
  . 1>&2
