#!/bin/bash

set -e

readonly LLVMCC=`which clang-10`
readonly LLVMCXX=`which clang++-10`
readonly LLVM_CONFIG=`ls ${RUSTC_DIR}/build/x86_*/llvm/bin/llvm-config`

git clone https://github.com/klee/klee-uclibc.git
cd klee-uclibc
readonly UCLIBC_DIR=`pwd`
./configure --make-llvm-lib --with-cc="${LLVMCC}" --with-llvm-config="${LLVM_CONFIG}"
make -j 4
cd ..

git clone --no-checkout https://github.com/klee/klee.git
cd klee
git checkout ${KLEE_VERSION}

mkdir build
cd build
cmake \
  -DCMAKE_INSTALL_PREFIX=/usr \
  -DENABLE_SOLVER_STP=ON \
  -DENABLE_KLEE_UCLIBC=ON \
  -DENABLE_POSIX_RUNTIME=ON \
  -DKLEE_UCLIBC_PATH="${UCLIBC_DIR}" \
  -DLLVMCC="${LLVMCC}" \
  -DLLVMCXX="${LLVMCXX}" \
  -DLLVM_CONFIG_BINARY="${LLVM_CONFIG}" \
  -DENABLE_UNIT_TESTS=ON \
  -DGTEST_SRC_DIR=${GTEST_DIR} \
  ..
make -j 4
make check
sudo make install
