#!/bin/bash

set -e

git clone https://github.com/klee/klee.git
cd klee

mkdir build
cd build
cmake \
  -DCMAKE_INSTALL_PREFIX=/usr \
  -DENABLE_SOLVER_STP=ON \
  -DLLVMCC=`which clang` \
  -DENABLE_KLEE_UCLIBC=OFF \
  -DLLVM_CONFIG_BINARY=`ls ${RUSTC_DIR}/build/x86_*/llvm/bin/llvm-config` \
  -DENABLE_UNIT_TESTS=ON \
  -DGTEST_SRC_DIR=/root/klee/googletest-release-1.7.0 \
  ..
make -j
make check
make install
