#! /usr/bin/env bash

set -e
set -x

(cd demos/simple/annotations; ./verify.sh)
(cd demos/simple/klee; ./verify.sh)
(cd demos/simple/seahorn; ./verify.sh)
(cd demos/simple/errors; ./verify.sh)

readonly FLAGS="--backend=klee --verbose --clean"
cargo-verify ${FLAGS} --tests --manifest-path=verification-annotations/Cargo.toml
cargo-verify ${FLAGS} --tests --manifest-path=compatibility-test/Cargo.toml
cargo-verify ${FLAGS} --tests --manifest-path=demos/bottlenecks/bornholt2018-1/Cargo.toml
cargo-verify ${FLAGS} --tests --manifest-path=demos/simple/ffi/Cargo.toml
cargo-verify ${FLAGS} -v -v -v --manifest-path=demos/simple/argv/Cargo.toml -- foo foo
cargo verify ${FLAGS} --tests --manifest-path=demos/bottlenecks/merging/Cargo.toml --backend-flags=--use-merge
cargo verify ${FLAGS} --tests --manifest-path=demos/bottlenecks/regex/Cargo.toml
cargo-verify ${FLAGS} --tests --manifest-path=demos/simple/string/Cargo.toml

# Test the --backend-flags and --replace-backend-flags options.
# Note the use of handlebars and passing args to main (foo foo).
cargo-verify ${FLAGS} --backend-flags='--exit-on-error,--entry-point,{entry},--libc=klee,--silent-klee-assume,--disable-verify,--output-dir,{output_dir},{file},foo,foo' --replace-backend-flags -v -v -v --script run.sh --manifest-path=demos/simple/argv/Cargo.toml

echo Regression test successful
